name: .NET Core

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install global tool
      run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0
    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
